name: frontend

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        RUNTIME_ENV: local
    environment:
      BUILD_VERSION: local
      # host.docker.internal resolves to the Mac host, since the backend runs outside this container
      ACROSS_SERVER_HOST: host.docker.internal
      ACROSS_SERVER_ID: a13bbcdd-798d-43cd-bb2a-6b10347db2a3
      ACROSS_SERVER_SECRET: local-service-account-key
    command: node build
    ports:
      - 5173:3000
