name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2                                 # name of AWS region
  ECR_REPOSITORY: across-frontend                       # name of ECR repo
  ECS_SERVICE: across-frontend-prod                     # name of the service
  ECS_CLUSTER: across-frontend                          # name of the cluster
  ECS_TASK_DEFINITION: .aws/deploy/task-definition.json # path of the JSON task definition
  CONTAINER_NAME: "across-frontend"                     # name of the container name in the task definition

jobs:
  deploy:
    name: Deploy to AWS ECR and ECS
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE_ARN }}
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image-frontend.outputs.image }}
          # if a second container image needs to be replaced
          # we should chain another amazon-ecs-render-task-definition@v1 action after this
          # using the output from this action as task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true