name: Deploy to AWS ECR

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      manual_version_tag:
        description: "Manual Version String for Container"
        required: false
        default: ''

env:
  # Is this a production or development deployment?
  # Production deployments are triggered by a release
  # Dev deployments will use a manual version tag 
  IS_PROD_OR_DEV: "${{ github.event_name == 'release'  && 'prod' || 'dev' }}"
  # name of AWS region
  AWS_REGION: us-east-2
  # name of ECR repo
  ECR_REPOSITORY: across-frontend                       

jobs:
  deploy:
    name: Deploy to AWS ECR and ECS
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git describe --tags
        id: ghd
        uses: proudust/gh-describe@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE_ARN }}
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # use manual_version_tag for dev when it is present
          GIT_VERSION: ${{ github.env.IS_PROD_OR_DEV == 'dev' && github.event.inputs.manual_version_tag != '' && github.event.inputs.manual_version_tag || steps.ghd.outputs.describe }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY-$IS_PROD_OR_DEV:$GIT_VERSION \
            --build-arg GIT_VERSION=$GIT_VERSION \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY-$IS_PROD_OR_DEV:$GIT_VERSION
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY-$IS_PROD_OR_DEV:$GIT_VERSION" >> $GITHUB_OUTPUT
          